# envoi/aws/envoi-aws-vpc-create
# VPC_NAME - Default envoi-distribution-cloud
export VPC_NAME=""
# VPC_TAGS - Key=Name,Value=${VPC_NAME}
export VPC_TAGS=""
# VPC_CIDR_PREFIX - 10.10.1
export VPC_CIDR_PREFIX=""
# VPC_CIDR - ${VPC_CIDR_PREFIX}.0/24
export VPC_CIDR=""


# envoi/aws/envoi-aws-cloudformation-create
# BUCKET_NAME
export BUCKET_NAME=""


# envoi/aws/envoi-aws-docdb-create-instance
# DEPLOY_DOCDB_ENGINE=docdb
export DEPLOY_DOCDB_ENGINE=""


# envoi/aws/envoi-aws-elasticsearch-create-domain
# ES_DOMAIN_NAME=${ES_DOMAIN_NAME:-envoi-dev}
export ES_DOMAIN_NAME=${ES_DOMAIN_NAME:-envoi-dev}
# ES_VOLUME_SIZE=${ES_VOLUME_SIZE:-10}
export ES_VOLUME_SIZE=${ES_VOLUME_SIZE:-10}
# ES_VERSION=${ES_VERSION:-7.10}
export ES_VERSION=${ES_VERSION:-7.10}
# ES_ADMIN_IAM_ARN=arn:aws:iam::833740154547:role/envoi-services-test-role
export ES_ADMIN_IAM_ARN=arn:aws:iam::833740154547:role/envoi-services-test-role
# ES_INSTANCE_TYPE=${ES_INSTANCE_TYPE:-t3.medium.elasticsearch}
export ES_INSTANCE_TYPE=${ES_INSTANCE_TYPE:-t3.medium.elasticsearch}
# ENVOI_AWS_REGION=${ENVOI_AWS_REGION:-us-east-1}
export ENVOI_AWS_REGION=${ENVOI_AWS_REGION:-us-east-1}
# ENVOI_AWS_ACCOUNT_ID=${ENVOI_AWS_ACCOUNT_ID:-833740154547}
export ENVOI_AWS_ACCOUNT_ID=${ENVOI_AWS_ACCOUNT_ID:-833740154547}


# envoi/aws/envoi-aws-docdb-create-cluster
# DEPLOY_DOCDB_CLUSTER_IDENTIFIER
export DEPLOY_DOCDB_CLUSTER_IDENTIFIER=""
# DEPLOY_DOCDB_INSTANCE_IDENTIFIER
export DEPLOY_DOCDB_INSTANCE_IDENTIFIER=""
# DEPLOY_DOCDB_AVAILABILITY_ZONE
export DEPLOY_DOCDB_AVAILABILITY_ZONE=""
# DEPLOY_DOCDB_DB_INSTANCE_CLASS
export DEPLOY_DOCDB_DB_INSTANCE_CLASS=""
# DEPLOY_DOCDB_ENGINE
export DEPLOY_DOCDB_ENGINE=""


# envoi/aws/envoi-aws-docdb-create-instance
# # DEPLOY_DOCDB_CLUSTER_IDENTIFIER
# export DEPLOY_DOCDB_CLUSTER_IDENTIFIER=""
# # DEPLOY_DOCDB_INSTANCE_IDENTIFIER
# export DEPLOY_DOCDB_INSTANCE_IDENTIFIER=""
# # DEPLOY_DOCDB_AVAILABILITY_ZONE
# export DEPLOY_DOCDB_AVAILABILITY_ZONE=""
# # DEPLOY_DOCDB_DB_INSTANCE_CLASS
# export DEPLOY_DOCDB_DB_INSTANCE_CLASS=""
# # DEPLOY_DOCDB_ENGINE
# export DEPLOY_DOCDB_ENGINE=""


# envoi/aws/envoi-aws-opensearch-create-domain
# # OS_DOMAIN_NAME=${OS_DOMAIN_NAME:-"envoi-analytics"}
# export OS_DOMAIN_NAME=${OS_DOMAIN_NAME:-"envoi-analytics"}
# # OS_ENGINE_VERSION=${OS_ENGINE_VERSION:-"OpenSearch_1.2"}
# export OS_ENGINE_VERSION=${OS_ENGINE_VERSION:-"OpenSearch_1.2"}
# # OS_INSTANCE_TYPE=${OS_INSTANCE_TYPE:-"r6g.large.search"}
# export OS_INSTANCE_TYPE=${OS_INSTANCE_TYPE:-"r6g.large.search"}
# # OS_INSTANCE_COUNT=${OS_INSTANCE_COUNT:-2}
# export OS_INSTANCE_COUNT=${OS_INSTANCE_COUNT:-2}
# # OS_EBS_VOLUME_TYPE=${OS_EBS_VOLUME_TYPE:-"gp3"}
# export OS_EBS_VOLUME_TYPE=${OS_EBS_VOLUME_TYPE:-"gp3"}
# # OS_EBS_VOLUME_SIZE=${OS_EBS_VOLUME_SIZE:-100}
# export OS_EBS_VOLUME_SIZE=${OS_EBS_VOLUME_SIZE:-100}
# # OS_EBS_IOPS=${OS_EBS_IOPS:-3500}
# export OS_EBS_IOPS=${OS_EBS_IOPS:-3500}
# # OS_EBS_THROUGHPUT=${OS_EBS_THROUGHPUT:-125}
# export OS_EBS_THROUGHPUT=${OS_EBS_THROUGHPUT:-125}


# envoi/aws/envoi-aws-rds-aurora-mysql-create-cluster
# # DB_MASTER_USERNAME=${DB_MASTER_USERNAME:-admin}
# export DB_MASTER_USERNAME=${DB_MASTER_USERNAME:-admin}
# # DB_MASTER_PASSWORD=${DB_MASTER_PASSWORD}
# export DB_MASTER_PASSWORD=""
# # DB_CLUSTER_IDENTIFIER=${DB_CLUSTER_IDENTIFIER:-sample-cluster}
# export DB_CLUSTER_IDENTIFIER=${DB_CLUSTER_IDENTIFIER:-sample-cluster}
# # DB_INSTANCE_IDENTIFIER=${DB_INSTANCE_IDENTIFIER:-sample-instance}
# export DB_INSTANCE_IDENTIFIER=${DB_INSTANCE_IDENTIFIER:-sample-instance}
# # DB_SUBNET_GROUP_NAME=${DB_SUBNET_GROUP_NAME:-default}
# export DB_SUBNET_GROUP_NAME=${DB_SUBNET_GROUP_NAME:-default}
# # # DB_SECURITY_GROUP_IDS=${DB_SECURITY_GROUP_IDS
# export DB_SECURITY_GROUP_IDS=""
# # DB_PARAMETER_GROUP_NAME=${DB_PARAMETER_GROUP_NAME:-default}
# export DB_PARAMETER_GROUP_NAME=${DB_PARAMETER_GROUP_NAME:-default}
# # DB_ENGINE=${DB_ENGINE:-aurora-mysql}
# export DB_ENGINE=${DB_ENGINE:-aurora-mysql}
# # DB_ENGINE_VERSION=${DB_ENGINE_VERSION:-5.7}
# export DB_ENGINE_VERSION=${DB_ENGINE_VERSION:-5.7}


# envoi/aws/envoi-aws-rds-aurora-postgres-create-cluster
# # DB_MASTER_USERNAME=${DB_MASTER_USERNAME:-admin}
# export DB_MASTER_USERNAME=${DB_MASTER_USERNAME:-admin}
# # DB_MASTER_PASSWORD=${DB_MASTER_PASSWORD}
# export DB_MASTER_PASSWORD=""
# # DB_CLUSTER_IDENTIFIER=${DB_CLUSTER_IDENTIFIER:-sample-cluster}
# export DB_CLUSTER_IDENTIFIER=${DB_CLUSTER_IDENTIFIER:-sample-cluster}
# # DB_INSTANCE_IDENTIFIER=${DB_INSTANCE_IDENTIFIER:-sample-instance}
# export DB_INSTANCE_IDENTIFIER=${DB_INSTANCE_IDENTIFIER:-sample-instance}
# # DB_SUBNET_GROUP_NAME=${DB_SUBNET_GROUP_NAME:-default}
# export DB_SUBNET_GROUP_NAME=${DB_SUBNET_GROUP_NAME:-default}
# # # DB_SECURITY_GROUP_IDS=${DB_SECURITY_GROUP_IDS
# export DB_SECURITY_GROUP_IDS=""
# # DB_PARAMETER_GROUP_NAME=${DB_PARAMETER_GROUP_NAME:-default}
# export DB_PARAMETER_GROUP_NAME=${DB_PARAMETER_GROUP_NAME:-default}
# # DB_ENGINE=${DB_ENGINE:-aurora-postgresql}
# export DB_ENGINE=${DB_ENGINE:-aurora-postgresql}
# # DB_ENGINE_VERSION=${DB_ENGINE_VERSION:-9.7}
# export DB_ENGINE_VERSION=${DB_ENGINE_VERSION:-9.7}


# envoi/aws/envoi-aws-s3-create-buckets
# ENVOI_ENVOI_S3_BUCKET_NAME_PREFIX=${1:-$ENVOI_ENVOI_S3_BUCKET_NAME_PREFIX}
export ENVOI_ENVOI_S3_BUCKET_NAME_PREFIX=""

# export ENVOI_S3_SOURCE_BUCKET_NAME=${ENVOI_ENVOI_S3_BUCKET_NAME_PREFIX}-source
# export ENVOI_S3_SOURCE_BUCKET_NAME=${ENVOI_ENVOI_S3_BUCKET_NAME_PREFIX}-archive
# export ENVOI_S3_PROXIES_BUCKET_NAME=${ENVOI_ENVOI_S3_BUCKET_NAME_PREFIX}-proxies
# export ENVOI_S3_IMAGES_BUCKET_NAME=${ENVOI_ENVOI_S3_BUCKET_NAME_PREFIX}-images
# export ENVOI_S3_COMMON_BUCKET_NAME=${ENVOI_ENVOI_S3_BUCKET_NAME_PREFIX}-common
# export ENVOI_S3_SCREENING_BUCKET_NAME=${ENVOI_ENVOI_S3_BUCKET_NAME_PREFIX}-screening-wui
# export ENVOI_S3_SUBMISSION_BUCKET_NAME=${ENVOI_ENVOI_S3_BUCKET_NAME_PREFIX}-submission-wui
# export ENVOI_S3_ADMIN_BUCKET_NAME=${ENVOI_ENVOI_S3_BUCKET_NAME_PREFIX}-admin-wui
# export ENVOI_S3_MEETING_BUCKET_NAME=${ENVOI_ENVOI_S3_BUCKET_NAME_PREFIX}-meetings-wui
# export ENVOI_S3_SCHEDULER_BUCKET_NAME=${ENVOI_ENVOI_S3_BUCKET_NAME_PREFIX}-scheduler-wui
# export ENVOI_S3_CHANNEL_BUCKET_NAME=${ENVOI_ENVOI_S3_BUCKET_NAME_PREFIX}-channel-wui
# export ENVOI_S3_TRANSFER_SERVER_BUCKET_NAME=${ENVOI_ENVOI_S3_BUCKET_NAME_PREFIX}-transfer-service-wui
# export ENVOI_S3_MEDIAEDGE_BUCKET_NAME=${ENVOI_ENVOI_S3_BUCKET_NAME_PREFIX}-media-edge-wui
