AWS_ACCOUNT_ID=${AWS_ACCOUNT_ID:-$(aws sts get-caller-identity --query Account --output text)}
AWS_REGION=${AWS_REGION:-us-east-1}
ENVOI_ACCOUNT_ID=833740154547

DEPLOYMENT_NAME=envoi

# Envoi VPC
ENVOI_VPC_NAME=${DEPLOYMENT_NAME}
ENVOI_VPC_CIDR_PREFIX=10.10.1
ENVOI_VPC_CIDR=${VPC_CIDR_PREFIX}.0/24
ENVOI_VPC_PRIVATE_SUBNET_1_CIDR_BLOCK=${VPC_CIDR_PREFIX}.0/26
ENVOI_VPC_PRIVATE_SUBNET_2_CIDR_BLOCK=${VPC_CIDR_PREFIX}.64/26
ENVOI_VPC_PUBLIC_SUBNET_1_CIDR_BLOCK=${VPC_CIDR_PREFIX}.128/26
ENVOI_VPC_PUBLIC_SUBNET_2_CIDR_BLOCK=${VPC_CIDR_PREFIX}.192/26


# Envoi DocumentDB
ENVOI_DOCDB_ENGINE=docdb
ENVOI_DOCDB_CLUSTER_IDENTIFIER=${DEPLOYMENT_NAME}
ENVOI_DOCDB_INSTANCE_IDENTIFIER=${DEPLOYMENT_NAME}
ENVOI_DOCDB_AVAILABILITY_ZONE=us-east-1a
ENVOI_DOCDB_INSTANCE_CLASS=r4
ENVOI_DOCDB_MASTER_USERNAME=dbAdmin


# Envoi OpenSearch
ENVOI_OS_DOMAIN_NAME=${DEPLOYMENT_NAME}
ENVOI_OS_ENGINE_VERSION=OpenSearch_1.2
ENVOI_OS_MASTER_USERNAME=dbAdmin
ENVOI_OS_INSTANCE_TYPE=r6g.large.search
ENVOI_OS_INSTANCE_COUNT=2
ENVOI_OS_EBS_VOLUME_TYPE=gp3
ENVOI_OS_EBS_VOLUME_SIZE=10
ENVOI_OS_EBS_IOPS=1000
ENVOI_OS_EBS_THROUGHPUT=10
ENVOI_OS_EBS_VOLUME_TAGS=Name=#{ENVOI_OS_DOMAIN_NAME}

# ENVOI_RDS_AURORA_MYSQL_
ENVOI_AMYSQL_MASTER_USERNAME=dbAdmin
ENVOI_AMYSQL_MASTER_PASSWORD=""
ENVOI_AMYSQL_CLUSTER_IDENTIFIER=${DEPLOYMENT_NAME}
ENVOI_AMYSQL_INSTANCE_IDENTIFIER=${DEPLOYMENT_NAME}
ENVOI_AMYSQL_SUBNET_GROUP_NAME=default
# ENVOI_AMYSQL_SECURITY_GROUP_IDS=${ENVOI_AMYSQL_SECURITY_GROUP_IDS
ENVOI_AMYSQL_PARAMETER_GROUP_NAME=default
ENVOI_AMYSQL_ENGINE_VERSION=5.7

# ENVOI_RDS_AURORA_POSTGRES_
ENVOI_APOSTGRES_MASTER_USERNAME=dbAdmin
ENVOI_APOSTGRES_MASTER_PASSWORD=""
ENVOI_APOSTGRES_CLUSTER_IDENTIFIER=${DEPLOYMENT_NAME}
ENVOI_APOSTGRES_INSTANCE_IDENTIFIER=${DEPLOYMENT_NAME}
ENVOI_APOSTGRES_SUBNET_GROUP_NAME=default
# ENVOI_APOSTGRES_SECURITY_GROUP_IDS=${ENVOI_APOSTGRES_SECURITY_GROUP_IDS
ENVOI_APOSTGRES_PARAMETER_GROUP_NAME=defai;t
ENVOI_APOSTGRES_ENGINE_VERSION=9.7

# Envoi S3 Buckets
ENVOI_ENVOI_S3_BUCKET_NAME_PREFIX=${DEPLOYMENT_NAME}-${AWS_ACCOUNT_ID}
ENVOI_S3_SOURCE_BUCKET_NAME=${ENVOI_ENVOI_S3_BUCKET_NAME_PREFIX}-source
ENVOI_S3_SOURCE_BUCKET_NAME=${ENVOI_ENVOI_S3_BUCKET_NAME_PREFIX}-archive
ENVOI_S3_PROXIES_BUCKET_NAME=${ENVOI_ENVOI_S3_BUCKET_NAME_PREFIX}-proxies
ENVOI_S3_IMAGES_BUCKET_NAME=${ENVOI_ENVOI_S3_BUCKET_NAME_PREFIX}-images
ENVOI_S3_COMMON_BUCKET_NAME=${ENVOI_ENVOI_S3_BUCKET_NAME_PREFIX}-common
ENVOI_S3_SCREENING_BUCKET_NAME=${ENVOI_ENVOI_S3_BUCKET_NAME_PREFIX}-screening-wui
ENVOI_S3_SUBMISSION_BUCKET_NAME=${ENVOI_ENVOI_S3_BUCKET_NAME_PREFIX}-submission-wui
ENVOI_S3_ADMIN_BUCKET_NAME=${ENVOI_ENVOI_S3_BUCKET_NAME_PREFIX}-admin-wui
ENVOI_S3_MEETING_BUCKET_NAME=${ENVOI_ENVOI_S3_BUCKET_NAME_PREFIX}-meetings-wui
ENVOI_S3_SCHEDULER_BUCKET_NAME=${ENVOI_ENVOI_S3_BUCKET_NAME_PREFIX}-scheduler-wui
ENVOI_S3_CHANNEL_BUCKET_NAME=${ENVOI_ENVOI_S3_BUCKET_NAME_PREFIX}-channel-wui
ENVOI_S3_TRANSFER_SERVER_BUCKET_NAME=${ENVOI_ENVOI_S3_BUCKET_NAME_PREFIX}-transfer-service-wui
ENVOI_S3_MEDIAEDGE_BUCKET_NAME=${ENVOI_ENVOI_S3_BUCKET_NAME_PREFIX}-media-edge-wui

