#!/usr/bin/env bash
# shellcheck disable=SC2155
export ENVOI_AWS_ACCOUNT_ID=833740154547

export AWS_ACCOUNT_ID=${AWS_ACCOUNT_ID:-$(aws sts get-caller-identity --query Account --output text)}
export AWS_ACCOUNT_ALIAS=${AWS_ACCOUNT_ALIAS:-$(aws iam list-account-aliases --query AccountAliases --output text)}
AWS_ACCOUNT_ALIAS=${AWS_ACCOUNT_ALIAS:-$AWS_ACCOUNT_ID}
export AWS_REGION=${AWS_REGION:-us-east-1}

export ENVOI_DEPLOYMENT_NAME_PREFIX=${ENVOI_DEPLOYMENT_NAME_PREFIX:-envoi}
export ENVOI_DEPLOYMENT_ENV_NAME=${ENVOI_DEPLOYMENT_ENV_NAME:-dev} # Suggested values are dev and prod.
export ENVOI_DEPLOYMENT_ID=${ENVOI_DEPLOYMENT_ID:-$(date "+%Y%m%d%H%M%S")}
export ENVOI_DEPLOYMENT_NAME="${ENVOI_DEPLOYMENT_NAME_PREFIX}-${ENVOI_DEPLOYMENT_ENV_NAME}-${ENVOI_DEPLOYMENT_ID}"

# Envoi VPC
export ENVOI_VPC_ID=${ENVOI_VPC_ID:-""}
export ENVOI_VPC_NAME=${ENVOI_DEPLOYMENT_NAME}
export ENVOI_VPC_CIDR_PREFIX=10.10.1
export ENVOI_VPC_CIDR=${VPC_CIDR_PREFIX}.0/24
export ENVOI_VPC_PRIVATE_SUBNET_1_CIDR_BLOCK=${ENVOI_VPC_CIDR_PREFIX}.0/26
export ENVOI_VPC_PRIVATE_SUBNET_2_CIDR_BLOCK=${ENVOI_VPC_CIDR_PREFIX}.64/26
export ENVOI_VPC_PUBLIC_SUBNET_1_CIDR_BLOCK=${ENVOI_VPC_CIDR_PREFIX}.128/26
export ENVOI_VPC_PUBLIC_SUBNET_2_CIDR_BLOCK=${ENVOI_VPC_CIDR_PREFIX}.192/26

# Envoi DocumentDB
export ENVOI_DOCDB_CLUSTER_IDENTIFIER=${ENVOI_DEPLOYMENT_NAME}
export ENVOI_DOCDB_INSTANCE_IDENTIFIER=${ENVOI_DEPLOYMENT_NAME}
export ENVOI_DOCDB_AVAILABILITY_ZONE=us-east-1a
export ENVOI_DOCDB_INSTANCE_CLASS=r4
export ENVOI_DOCDB_MASTER_USERNAME=dbAdmin
export ENVOI_DOCDB_MASTER_PASSWORD="" # If left empty then one will be generated.

# Envoi DynamoDB
export ENVOI_DYNAMODB_SCHEMA_DIR=${ENVOI_DYNAMODB_SCHEMA_DIR:-"./schema/dynamodb"}

# Envoi OpenSearch
export ENVOI_OS_DOMAIN_NAME=${ENVOI_DEPLOYMENT_NAME}
export ENVOI_OS_ENGINE_VERSION=OpenSearch_1.2
export ENVOI_OS_MASTER_USERNAME=dbAdmin
export ENVOI_OS_INSTANCE_TYPE=r6g.large.search
export ENVOI_OS_INSTANCE_COUNT=2
export ENVOI_OS_EBS_VOLUME_TYPE=gp3
export ENVOI_OS_EBS_VOLUME_SIZE=10
export ENVOI_OS_EBS_IOPS=1000
export ENVOI_OS_EBS_THROUGHPUT=10
export ENVOI_OS_EBS_VOLUME_TAGS=Name=${ENVOI_OS_DOMAIN_NAME}

# ENVOI_RDS_AURORA_MYSQL
export ENVOI_AMYSQL_MASTER_USERNAME=dbAdmin
export ENVOI_AMYSQL_MASTER_PASSWORD="" # If left empty then one will be generated.
export ENVOI_AMYSQL_CLUSTER_IDENTIFIER=${ENVOI_DEPLOYMENT_NAME}
export ENVOI_AMYSQL_INSTANCE_IDENTIFIER=${ENVOI_DEPLOYMENT_NAME}
export ENVOI_AMYSQL_SUBNET_GROUP_NAME=default
# ENVOI_AMYSQL_SECURITY_GROUP_IDS=${ENVOI_AMYSQL_SECURITY_GROUP_IDS
export ENVOI_AMYSQL_CLUSTER_PARAMETER_GROUP_NAME=envoi-aurora-mysql-8-0-default
export ENVOI_AMYSQL_ENGINE_VERSION=8.0

# ENVOI_RDS_AURORA_POSTGRES_
export ENVOI_APOSTGRES_MASTER_USERNAME=dbAdmin
export ENVOI_APOSTGRES_MASTER_PASSWORD="" # If left empty then one will be generated.
export ENVOI_APOSTGRES_CLUSTER_IDENTIFIER=${ENVOI_DEPLOYMENT_NAME}
export ENVOI_APOSTGRES_INSTANCE_IDENTIFIER=${ENVOI_DEPLOYMENT_NAME}
export ENVOI_APOSTGRES_SUBNET_GROUP_NAME=default
# ENVOI_APOSTGRES_SECURITY_GROUP_IDS=${ENVOI_APOSTGRES_SECURITY_GROUP_IDS
export ENVOI_APOSTGRES_CLUSTER_PARAMETER_GROUP_NAME=envoi-aurora-postgres16-default
export ENVOI_APOSTGRES_ENGINE_VERSION=9.7

# Envoi Mongo
export ENVOI_MONGO_SCHEMA_DIR=${ENVOI_MONGO_SCHEMA_DIR:-"./schema/mongo"}

# Envoi S3 Buckets
export ENVOI_ENVOI_S3_BUCKET_NAME_PREFIX=${DEPLOYMENT_NAME_PREFIX}-${AWS_ACCOUNT_ALIAS}
export ENVOI_S3_SOURCE_BUCKET_NAME=${ENVOI_ENVOI_S3_BUCKET_NAME_PREFIX}-source
export ENVOI_S3_SOURCE_BUCKET_NAME=${ENVOI_ENVOI_S3_BUCKET_NAME_PREFIX}-archive
export ENVOI_S3_PROXIES_BUCKET_NAME=${ENVOI_ENVOI_S3_BUCKET_NAME_PREFIX}-proxies
export ENVOI_S3_IMAGES_BUCKET_NAME=${ENVOI_ENVOI_S3_BUCKET_NAME_PREFIX}-images
export ENVOI_S3_COMMON_BUCKET_NAME=${ENVOI_ENVOI_S3_BUCKET_NAME_PREFIX}-common
export ENVOI_S3_SCREENING_BUCKET_NAME=${ENVOI_ENVOI_S3_BUCKET_NAME_PREFIX}-screening-wui
export ENVOI_S3_SUBMISSION_BUCKET_NAME=${ENVOI_ENVOI_S3_BUCKET_NAME_PREFIX}-submission-wui
export ENVOI_S3_ADMIN_BUCKET_NAME=${ENVOI_ENVOI_S3_BUCKET_NAME_PREFIX}-admin-wui
export ENVOI_S3_MEETING_BUCKET_NAME=${ENVOI_ENVOI_S3_BUCKET_NAME_PREFIX}-meetings-wui
export ENVOI_S3_SCHEDULER_BUCKET_NAME=${ENVOI_ENVOI_S3_BUCKET_NAME_PREFIX}-scheduler-wui
export ENVOI_S3_CHANNEL_BUCKET_NAME=${ENVOI_ENVOI_S3_BUCKET_NAME_PREFIX}-channel-wui
export ENVOI_S3_TRANSFER_SERVER_BUCKET_NAME=${ENVOI_ENVOI_S3_BUCKET_NAME_PREFIX}-transfer-service-wui
export ENVOI_S3_MEDIA_EDGE_BUCKET_NAME=${ENVOI_ENVOI_S3_BUCKET_NAME_PREFIX}-media-edge-wui

# Switches
export ENVOI_DEPLOY_SHOULD_CREATE_DOCDB=${ENVOI_DEPLOY_SHOULD_CREATE_DOCDB:-true}
export ENVOI_DEPLOY_SHOULD_CREATE_OPEN_SEARCH=${ENVOI_DEPLOY_SHOULD_CREATE_OPEN_SEARCH:-true}
export ENVOI_DEPLOY_SHOULD_CREATE_RDS_AURORA_MYSQL=${ENVOI_DEPLOY_SHOULD_CREATE_RDS_AURORA_MYSQL:-true}
export ENVOI_DEPLOY_SHOULD_CREATE_RDS_AURORA_POSTGRES=${ENVOI_DEPLOY_SHOULD_CREATE_RDS_AURORA_POSTGRES:-true}
export ENVOI_DEPLOY_SHOULD_CREATE_S3_BUCKETS=${ENVOI_DEPLOY_SHOULD_CREATE_S3_BUCKETS:-true}
export ENVOI_DEPLOY_SHOULD_CREATE_VPC=${ENVOI_DEPLOY_SHOULD_CREATE_VPC:-true}

export ENVOI_DEPLOY_SHOULD_CREATE_MONGO_SECRET=${ENVOI_DEPLOY_SHOULD_CREATE_MONGO_SECRET:-${ENVOI_DEPLOY_SHOULD_CREATE_DOCDB}}
export ENVOI_DEPLOY_SHOULD_CREATE_MYSQL_SECRET=${ENVOI_DEPLOY_SHOULD_CREATE_MYSQL_SECRET:-${ENVOI_DEPLOY_SHOULD_CREATE_RDS_AURORA_MYSQL}}
export ENVOI_DEPLOY_SHOULD_CREATE_POSTGRES_SECRET=${ENVOI_DEPLOY_SHOULD_CREATE_POSTGRES_SECRET:-${ENVOI_DEPLOY_SHOULD_CREATE_RDS_AURORA_POSTGRES}}
